// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa7VDLiGihqkI1cJlfR2nKno2A9rsuO50',
    appId: '1:504178179550:android:2e5c95529ffb34d048714f',
    messagingSenderId: '504178179550',
    projectId: 'counter-realtime-eac96',
    databaseURL: 'https://counter-realtime-eac96-default-rtdb.firebaseio.com',
    storageBucket: 'counter-realtime-eac96.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYJ35AlWUyBnNQSyamnqdOV37fzTtGfz8',
    appId: '1:504178179550:ios:fdad2a7cd26ef69f48714f',
    messagingSenderId: '504178179550',
    projectId: 'counter-realtime-eac96',
    databaseURL: 'https://counter-realtime-eac96-default-rtdb.firebaseio.com',
    storageBucket: 'counter-realtime-eac96.appspot.com',
    iosBundleId: 'com.example.branchesTestingPd',
  );
}
