name: Firebase APP workflow

on:
  push:
    branches:
      - dev

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '12.x' # Changed to 12.x for better compatibility

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.x'
          channel: 'beta'

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Build Flutter APK
        run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v2
        with:
          name: apk-build
          path: build/app/outputs/flutter-apk

      - name: Deploy to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.5.0
        with:
          appId: ${{ secrets.APP_ID }}
          token: ${{ secrets.APP_TOKEN }}
          release_notes: "A new version"
          file: build/app/outputs/flutter-apk/app-release.apk
