name: Firebase APP workflow

on:
  push:
    branches:
      - dev

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '12'

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.x'
          channel: 'beta'

      - run: flutter pub get
      - run: flutter build apk --release

      - uses: actions/upload-artifact@v2
        with:
          name: apk-build
          path: build/app/outputs/flutter-apk

      - name: Deploy
        uses: wzieba/Firebase-Distribution-Github-Action@v1.5.0
        with:
          appId: ${{ secrets.APP_ID }}
          token: ${{ secrets.APP_TOKEN }}
          release_notes: "a new version"
          file: build/app/outputs/flutter-apk/app-release.apk