name: Firebase APP workflow

on:
  push:
    branches:
      - dev

jobs:
  firebase_app:
    name: Run Firebase Workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '12'

      - name: Decode google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.JSON }}
        run: echo "$GOOGLE_SERVICES_JSON" > android/app/google-services.json

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.x' # Adjust to your Flutter version
          channel: 'stable'

      - run: flutter pub get
      - run: flutter build apk --release

      - uses: actions/upload-artifact@v2
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.APP_ID }}
          token: ${{ secrets.APP_TOKEN }}
          groups: testers
          file: build/app/outputs/flutter-apk/app-release.apk
