name: Build and Upload Flutter AAB

on:
  push:
    branches:
      - dev

jobs:
  build:
    name: Build Flutter AAB
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build AAB
        run: flutter build appbundle

      - name: Upload AAB
        uses: actions/upload-artifact@v2
        with:
          name: release-aab
          path: build/app/outputs/bundle/release/app-release.aab



#      - name: Upload AAB to Google Play
#        uses: r0adkll/upload-google-play@v1
#        with:
#          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT }}
#          packageName: your.package.name
#          track: production
#          bundleFile: app/build/outputs/bundle/release/app.aab
